
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package picoada;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TypeInteger = 13;
  public static final int elsif = 18;
  public static final int CerrarParentesis = 37;
  public static final int PuntoComa = 35;
  public static final int loop = 8;
  public static final int If = 16;
  public static final int Id = 30;
  public static final int TypeFloat = 11;
  public static final int coma = 44;
  public static final int Else = 19;
  public static final int OperadorRelacional = 29;
  public static final int string = 5;
  public static final int begin = 3;
  public static final int AbrirParentesis = 36;
  public static final int Put = 20;
  public static final int TypeBoolean = 14;
  public static final int end = 4;
  public static final int Return = 41;
  public static final int While = 9;
  public static final int EOL = 50;
  public static final int Float = 12;
  public static final int then = 17;
  public static final int For = 7;
  public static final int EOF = 0;
  public static final int Put_Line = 21;
  public static final int comillas = 48;
  public static final int DosPuntos = 34;
  public static final int Function = 40;
  public static final int is = 6;
  public static final int error = 1;
  public static final int diff = 28;
  public static final int When = 42;
  public static final int in = 26;
  public static final int or = 25;
  public static final int Integer = 10;
  public static final int CerrarBracket = 46;
  public static final int Get = 22;
  public static final int procedure = 2;
  public static final int punto = 47;
  public static final int ERROR = 52;
  public static final int AbrirBracket = 45;
  public static final int out = 27;
  public static final int and = 24;
  public static final int not = 23;
  public static final int ContString = 49;
  public static final int comentario = 51;
  public static final int AbrirCorchete = 38;
  public static final int OperadorSuma = 31;
  public static final int Boolean = 15;
  public static final int CerrarCorchete = 39;
  public static final int OperadorMultiplicacion = 32;
  public static final int asignacion = 33;
  public static final int Exit = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "procedure",
  "begin",
  "end",
  "string",
  "is",
  "For",
  "loop",
  "While",
  "Integer",
  "TypeFloat",
  "Float",
  "TypeInteger",
  "TypeBoolean",
  "Boolean",
  "If",
  "then",
  "elsif",
  "Else",
  "Put",
  "Put_Line",
  "Get",
  "not",
  "and",
  "or",
  "in",
  "out",
  "diff",
  "OperadorRelacional",
  "Id",
  "OperadorSuma",
  "OperadorMultiplicacion",
  "asignacion",
  "DosPuntos",
  "PuntoComa",
  "AbrirParentesis",
  "CerrarParentesis",
  "AbrirCorchete",
  "CerrarCorchete",
  "Function",
  "Return",
  "When",
  "Exit",
  "coma",
  "AbrirBracket",
  "CerrarBracket",
  "punto",
  "comillas",
  "ContString",
  "EOL",
  "comentario",
  "ERROR"
  };
}

