
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int not = 19;
  public static final int end = 5;
  public static final int is = 7;
  public static final int procedure = 2;
  public static final int Integer = 3;
  public static final int or = 21;
  public static final int bracketC = 17;
  public static final int bracketA = 16;
  public static final int equals = 18;
  public static final int punto = 9;
  public static final int EOF = 0;
  public static final int id = 8;
  public static final int assignment = 6;
  public static final int error = 1;
  public static final int abrirC = 14;
  public static final int cerrarC = 15;
  public static final int parentesisC = 13;
  public static final int puntos = 10;
  public static final int puntoC = 11;
  public static final int parentesisA = 12;
  public static final int begin = 4;
  public static final int and = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "procedure",
  "Integer",
  "begin",
  "end",
  "assignment",
  "is",
  "id",
  "punto",
  "puntos",
  "puntoC",
  "parentesisA",
  "parentesisC",
  "abrirC",
  "cerrarC",
  "bracketA",
  "bracketC",
  "equals",
  "not",
  "and",
  "or"
  };
}

